"""
GazeLens data pipeline.

Provides:
  - ScanpathLoader: reads _fixation_filtered.csv for a video, returns (N, 4) tensor
  - GazeLensDataset: loads temporal task QA JSONs + maps to scanpath CSVs
  - collate_fn: handles variable-length scanpaths (pad to max in batch)

QA JSON format (per entry):
  {
    "video_path": "...",
    "response_time": "[MM:SS - MM:SS]",
    "questions": [
      {
        "question": "...",
        "time_stamp": "MM:SS",
        "answer": "A",
        "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
        "task_type": "...",
        ...task-specific fields...
      }
    ]
  }

Fixation CSV fields (step 1.5 output):
  fixation_id, center_x, center_y, start_time_seconds, end_time_seconds, duration, ...

Task-to-clip mapping (per spec.md §3.3):
  - Past tasks (OTP, GSM, SR, NFI): [0, question_time]
  - FAP (future task):               [max(0, question_time - 60), question_time]
"""

import os
import csv
import json
import math
from pathlib import Path
from typing import List, Optional, Tuple, Dict, Any

import torch
from torch.utils.data import Dataset


# ---------------------------------------------------------------------------
# Task type registry
# ---------------------------------------------------------------------------

# Maps task_type string -> clip window strategy
#   "past"   = [0, question_time]
#   "window" = [max(0, question_time - 60), question_time]
#
# Two naming conventions exist in the wild:
#   Pipeline CamelCase: generated by qa_generation/*.py (e.g. "Object_Identification")
#   Benchmark snake_case: finalized QA files (e.g. "present_object_identification_easy")
# Both are listed so GazeLens handles QA JSONs from either source without misassigning
# clip windows (present tasks must use "window", not the "past" fallback).
_TASK_CLIP_STRATEGY: Dict[str, str] = {
    # ── Past tasks ──────────────────────────────────────────────────────────
    # Benchmark canonical names
    "past_object_transition_prediction": "past",       # OTP
    "past_gaze_sequence_matching": "past",             # GSM
    "past_scene_recall": "past",                       # SR
    "past_non_fixated_object_identification": "past",  # NFI
    # Pipeline CamelCase names (qa_generation/past.py)
    "Scanpath_Next_After_Group": "past",               # OTP / GSM
    "Scanpath_Transition_Pattern": "past",             # OTP variant
    "Scanpath_Never_Gazed": "past",                    # NFI
    "Scene_Reconstruction": "past",                    # SR
    # Lowercase aliases
    "scene_recall": "past",
    "scanpath_reasoning": "past",
    # ── Present tasks ────────────────────────────────────────────────────────
    # Benchmark canonical names
    "present_object_identification_easy": "window",    # OI-Easy
    "present_object_identification_hard": "window",    # OI-Hard
    "present_object_attribute_recognition": "window",  # OAR
    # Pipeline CamelCase names (qa_generation/present.py)
    "Object_Identification": "window",                 # OI (both easy and hard)
    "Object_Attribute": "window",                      # OAR
    # Lowercase aliases (legacy)
    "object_identification": "window",
    "object_attribute_recognition": "window",
    # ── Present / future tasks ───────────────────────────────────────────────
    # Benchmark canonical name
    "present_future_action_prediction": "window",      # FAP
    # Pipeline CamelCase names (qa_generation/future.py)
    "Future_Action_Prediction": "window",              # FAP
    "Object_Remind_Easy": "window",                    # object remind (future)
    "Object_Remind_Hard": "window",                    # object remind (future)
    # Lowercase aliases
    "future_action_prediction": "window",
    "FAP": "window",
    # ── Proactive tasks ─────────────────────────────────────────────────────
    "proactive_gaze_triggered_alert": "proactive",   # GTA
    "proactive_object_appearance_alert": "proactive", # OAA
}

# Tasks treated as "past" if task_type is missing
_DEFAULT_CLIP_STRATEGY = "past"

# Canonical task names for grouping
TASK_PAST = {"OTP", "GSM", "SR", "NFI"}
TASK_FUTURE = {"FAP"}
TASK_PRESENT = {"OI-Easy", "OI-Hard", "OAR"}


def _parse_timestamp(ts: str) -> float:
    """Convert 'MM:SS' or 'HH:MM:SS' or float-string to seconds."""
    parts = ts.strip().split(":")
    if len(parts) == 2:
        return int(parts[0]) * 60 + int(parts[1])
    elif len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
    else:
        return float(ts)


def _clip_strategy_for_question(q: Dict[str, Any]) -> str:
    """Return 'past' or 'window' based on the question's task_type."""
    task_type = q.get("task_type", "")
    if task_type in _TASK_CLIP_STRATEGY:
        return _TASK_CLIP_STRATEGY[task_type]
    # Fallback: check required_ability
    required = q.get("required_ability", "")
    if "future" in task_type.lower() or "future" in required.lower():
        return "window"
    return _DEFAULT_CLIP_STRATEGY


# ---------------------------------------------------------------------------
# ScanpathLoader
# ---------------------------------------------------------------------------

class ScanpathLoader:
    """
    Loads fixation data from a _fixation_filtered.csv file.

    Expected CSV columns (at minimum):
      fixation_id, center_x, center_y, start_time_seconds, end_time_seconds

    Optional columns used if present:
      duration

    Returns:
      (N, 4) float tensor: [center_x, center_y, midpoint_time, duration]
      sorted by fixation_id (or start_time_seconds if fixation_id absent).
    """

    def __init__(self, csv_path: str):
        self.csv_path = csv_path
        self._data: Optional[torch.Tensor] = None  # cached

    def load(self) -> torch.Tensor:
        """Load and return (N, 4) tensor. Cached after first call."""
        if self._data is not None:
            return self._data
        self._data = self._read_csv(self.csv_path)
        return self._data

    def load_clipped(self, start_time: float, end_time: float) -> torch.Tensor:
        """
        Load scanpath clipped to [start_time, end_time].

        Returns (M, 4) tensor where M <= N. If no fixations in window,
        returns a zero-row tensor of shape (0, 4).
        """
        data = self.load()
        if data.shape[0] == 0:
            return data
        # Midpoint time is column index 2
        t = data[:, 2]
        mask = (t >= start_time) & (t <= end_time)
        return data[mask]

    @staticmethod
    def _read_csv(path: str) -> torch.Tensor:
        """
        Parse the fixation CSV and return a (N, 4) float tensor.

        Handles:
          - Missing 'duration' column → set duration=0
          - Missing 'fixation_id' column → sort by start_time_seconds
          - 'start_time' / 'end_time' as aliases for start/end_time_seconds
        """
        rows: List[Tuple[float, float, float, float, float]] = []
        # (fixation_id_for_sort, x, y, midpoint_t, dur)

        try:
            with open(path, newline="", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                fieldnames = reader.fieldnames or []

                # Normalize column aliases
                has_start = "start_time_seconds" in fieldnames or "start_time" in fieldnames
                has_end = "end_time_seconds" in fieldnames or "end_time" in fieldnames
                has_dur = "duration" in fieldnames
                has_fid = "fixation_id" in fieldnames

                start_col = "start_time_seconds" if "start_time_seconds" in fieldnames else "start_time"
                end_col = "end_time_seconds" if "end_time_seconds" in fieldnames else "end_time"

                for row in reader:
                    try:
                        x = float(row["center_x"])
                        y = float(row["center_y"])
                        t_start = float(row[start_col]) if has_start else 0.0
                        t_end = float(row[end_col]) if has_end else t_start
                        mid_t = (t_start + t_end) / 2.0
                        dur = float(row["duration"]) if has_dur else (t_end - t_start)
                        fid = float(row["fixation_id"]) if has_fid else t_start
                        rows.append((fid, x, y, mid_t, dur))
                    except (ValueError, KeyError):
                        continue  # skip malformed rows

        except FileNotFoundError:
            return torch.zeros(0, 4)
        except Exception:
            return torch.zeros(0, 4)

        if not rows:
            return torch.zeros(0, 4)

        # Sort by fixation_id (or start_time if no fixation_id)
        rows.sort(key=lambda r: r[0])

        # Build tensor: [x, y, mid_t, dur]
        arr = torch.tensor([[r[1], r[2], r[3], r[4]] for r in rows], dtype=torch.float32)
        return arr


# ---------------------------------------------------------------------------
# GazeLensDataset
# ---------------------------------------------------------------------------

class GazeLensDataset(Dataset):
    """
    Dataset over temporal task QA entries.

    Each item is a flat (one question) sample:
      {
        "video_path":     str,
        "scanpath":       (N, 4) float tensor  [x, y, t, dur]  — clipped to clip window
        "question_text":  str,
        "options":        List[str],  e.g. ["A. ...", "B. ...", ...]
        "answer":         str,        single letter "A"/"B"/"C"/"D"
        "answer_idx":     int,        0/1/2/3
        "start_time":     float,      clip start (seconds)
        "end_time":       float,      clip end   (seconds)
        "question_time":  float,      question timestamp (seconds)
        "task_type":      str,
      }

    Args:
        qa_files:        list of paths to QA JSON files
        video_root:      root directory to resolve relative video paths
        fixation_root:   root directory to search for *_fixation_filtered.csv files
                         (if None, searches alongside the video)
        split:           "train"/"val"/"test" or None (use all)
        split_file:      optional JSON {"train": [...], "val": [...], "test": [...]}
                         where values are video basename lists
        min_fixations:   skip samples where scanpath has fewer than this many fixations
    """

    def __init__(
        self,
        qa_files: List[str],
        video_root: str = "",
        fixation_root: Optional[str] = None,
        split: Optional[str] = None,
        split_file: Optional[str] = None,
        min_fixations: int = 1,
    ):
        self.video_root = video_root
        self.fixation_root = fixation_root
        self.min_fixations = min_fixations

        # Load split whitelist if provided
        split_videos: Optional[set] = None
        if split_file and split and os.path.exists(split_file):
            with open(split_file) as f:
                splits = json.load(f)
            split_videos = set(splits.get(split, []))

        # Parse all QA entries into flat samples
        self.samples: List[Dict[str, Any]] = []
        self._scanpath_cache: Dict[str, ScanpathLoader] = {}

        for qa_path in qa_files:
            entries = self._load_qa_json(qa_path)
            for entry in entries:
                video_path = self._resolve_video_path(entry.get("video_path", ""))
                video_name = os.path.basename(video_path)

                # Apply split filter
                if split_videos is not None and video_name not in split_videos:
                    continue

                inferred_task_type = Path(qa_path).stem
                is_proactive = _TASK_CLIP_STRATEGY.get(
                    inferred_task_type, _DEFAULT_CLIP_STRATEGY
                ) == "proactive"

                for q in entry.get("questions", []):
                    if not q.get("task_type"):
                        q = {**q, "task_type": inferred_task_type}

                    if is_proactive:
                        for s in self._build_proactive_samples(q, video_path):
                            self.samples.append(s)
                    else:
                        sample = self._build_sample(entry, q, video_path)
                        if sample is not None:
                            self.samples.append(sample)

    # ------------------------------------------------------------------
    # Dataset protocol
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        sample = self.samples[idx].copy()
        video_path = sample["video_path"]
        start_time = sample["start_time"]
        end_time = sample["end_time"]

        # Load and clip scanpath
        loader = self._get_loader(video_path)
        scanpath = loader.load_clipped(start_time, end_time)

        if scanpath.shape[0] < self.min_fixations:
            # Return empty scanpath (training loop should handle this gracefully)
            scanpath = torch.zeros(0, 4)

        sample["scanpath"] = scanpath
        return sample

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_qa_json(self, path: str) -> List[Dict[str, Any]]:
        try:
            with open(path) as f:
                data = json.load(f)
            if isinstance(data, list):
                return data
            return [data]
        except Exception:
            return []

    def _resolve_video_path(self, raw_path: str) -> str:
        """Prefer absolute path; fall back to video_root + basename."""
        if os.path.isabs(raw_path) and os.path.exists(raw_path):
            return raw_path
        name = os.path.basename(raw_path)
        candidate = os.path.join(self.video_root, name)
        return candidate  # May not exist; caller handles missing files

    def _get_loader(self, video_path: str) -> ScanpathLoader:
        """Return a cached ScanpathLoader for the given video."""
        if video_path not in self._scanpath_cache:
            csv_path = self._find_fixation_csv(video_path)
            self._scanpath_cache[video_path] = ScanpathLoader(csv_path)
        return self._scanpath_cache[video_path]

    def _find_fixation_csv(self, video_path: str) -> str:
        """
        Search for the fixation CSV associated with a video.

        Search order (for each root in fixation_root, which may be a
        space- or colon-separated list of paths):
          1. <root>/<video_stem>_fixation_filtered.csv
          2. <root>/<video_stem>/<video_stem>_fixation_filtered.csv
        Then falls back to the video directory.

        Returns the first path found, or a non-existent path if none found
        (ScanpathLoader handles missing files gracefully).
        """
        stem = Path(video_path).stem
        candidates = []

        if self.fixation_root:
            # Support space- or colon-separated list of roots
            import re as _re
            roots = _re.split(r'[:\s]+', self.fixation_root.strip())
            for root in roots:
                if root:
                    candidates.append(os.path.join(root, f"{stem}_fixation_filtered.csv"))
                    candidates.append(os.path.join(root, stem, f"{stem}_fixation_filtered.csv"))

        video_dir = os.path.dirname(video_path)
        if video_dir:
            candidates.append(os.path.join(video_dir, f"{stem}_fixation_filtered.csv"))

        for path in candidates:
            if os.path.exists(path):
                return path

        # Return default (non-existent) path; ScanpathLoader returns empty tensor
        return candidates[0] if candidates else f"{stem}_fixation_filtered.csv"

    def _build_sample(
        self,
        entry: Dict[str, Any],
        q: Dict[str, Any],
        video_path: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Build a flat sample dict from an entry + question dict.
        Returns None if required fields are missing or invalid.
        """
        question_text = q.get("question", "").strip()
        if not question_text:
            return None

        # Parse question timestamp
        ts_str = q.get("time_stamp", "")
        if not ts_str:
            return None
        try:
            question_time = _parse_timestamp(ts_str)
        except (ValueError, IndexError):
            return None

        # Answer
        answer = q.get("answer", "").strip().upper()
        if answer not in ("A", "B", "C", "D"):
            return None
        answer_idx = ord(answer) - ord("A")

        # Options
        options = q.get("options", [])
        if not options:
            return None

        # Clip window
        strategy = _clip_strategy_for_question(q)
        if strategy == "past":
            start_time = 0.0
            end_time = question_time
        else:  # "window"
            start_time = max(0.0, question_time - 60.0)
            end_time = question_time

        task_type = q.get("task_type", "")

        return {
            "video_path": video_path,
            "question_text": question_text,
            "options": options,
            "answer": answer,
            "answer_idx": answer_idx,
            "start_time": start_time,
            "end_time": end_time,
            "question_time": question_time,
            "task_type": task_type,
        }

    def _build_proactive_samples(
        self,
        q: Dict[str, Any],
        video_path: str,
    ) -> List[Dict[str, Any]]:
        """Expand a proactive question into one MCQA sample per test_info point.

        Each test point becomes: A. Yes / B. No, with answer based on type (1=A, 0=B).
        The video clip is [0, realtime_seconds].
        """
        question_text = q.get("question", "").strip()
        if not question_text:
            return []

        task_type = q.get("task_type", "")
        test_info = q.get("test_info", [])
        if not test_info:
            return []

        # Wrap the original question in the alert-decision framing
        prompt_question = (
            f"{question_text} Based on the video so far, "
            f"should the alert be triggered?"
        )

        samples = []
        for ti in test_info:
            realtime = ti.get("realtime", "")
            ground_truth = ti.get("type")  # 0 or 1
            if ground_truth is None or not realtime:
                continue

            # Clip range
            clip = ti.get("input_video_clip")
            if clip:
                start_time = float(clip[0])
                end_time = float(clip[1])
            else:
                start_time = 0.0
                end_time = _parse_timestamp(realtime)

            if end_time <= start_time:
                end_time = start_time + 1.0

            # MCQA: A=Yes, B=No
            answer = "A" if ground_truth == 1 else "B"
            answer_idx = 0 if ground_truth == 1 else 1

            samples.append({
                "video_path": video_path,
                "question_text": prompt_question,
                "options": ["A. Yes", "B. No"],
                "answer": answer,
                "answer_idx": answer_idx,
                "start_time": start_time,
                "end_time": end_time,
                "question_time": end_time,
                "task_type": task_type,
            })

        return samples


# ---------------------------------------------------------------------------
# collate_fn
# ---------------------------------------------------------------------------

def collate_fn(
    batch: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Collate a list of GazeLensDataset samples into a batch.

    Variable-length scanpaths are padded with zeros to the max length in the
    batch. A 'scanpath_lengths' tensor records the true length of each sample.

    Returns dict with keys:
      scanpaths:         (B, N_max, 4) float tensor
      scanpath_lengths:  (B,) long tensor
      answer_idxs:       (B,) long tensor
      video_paths:       List[str]
      question_texts:    List[str]
      options:           List[List[str]]
      answers:           List[str]
      start_times:       List[float]
      end_times:         List[float]
      question_times:    List[float]
      task_types:        List[str]
    """
    lengths = [s["scanpath"].shape[0] for s in batch]
    max_len = max(lengths) if lengths else 1
    max_len = max(max_len, 1)  # avoid zero-length tensor

    B = len(batch)
    padded = torch.zeros(B, max_len, 4, dtype=torch.float32)
    for i, s in enumerate(batch):
        sp = s["scanpath"]
        n = sp.shape[0]
        if n > 0:
            padded[i, :n] = sp

    return {
        "scanpaths": padded,
        "scanpath_lengths": torch.tensor(lengths, dtype=torch.long),
        "answer_idxs": torch.tensor([s["answer_idx"] for s in batch], dtype=torch.long),
        "video_paths": [s["video_path"] for s in batch],
        "question_texts": [s["question_text"] for s in batch],
        "options": [s["options"] for s in batch],
        "answers": [s["answer"] for s in batch],
        "start_times": [s["start_time"] for s in batch],
        "end_times": [s["end_time"] for s in batch],
        "question_times": [s["question_time"] for s in batch],
        "task_types": [s["task_type"] for s in batch],
    }
